version: '3.3'

services:
  solar-db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    container_name: solar-db-container
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: solardb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root12345
    ports:
      - ${DB_PORT_PUBLIC}:3306
    volumes:
      - ${LOCAL_DATA_DIR_BD}:/var/lib/mysql
    #net: ${NETWORK}
    networks:
      solar-network:
        ipv4_address: 172.19.0.252
    healthcheck:
      test: "mariadb $$MYSQL_DATABASE -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 5s
      timeout: 5s
      retries: 10

  adminer-bd:
    image: adminer
    container_name: adminer-bd-container
    restart: always
    ports:
      - 8080:8080
    networks:
      solar-network:
        ipv4_address: 172.19.0.253

#  solar-web:
#    container_name: solar-web-container
#    build: .
#    image: solar-web-api:latest
    #environment:
    #  MYSQL_HOST: ${MYSQL_HOST}
    #  MYSQL_USER: admin
    #  MYSQL_PASSWORD: root12345
    #  MYSQL_DB: solardb
    #  FLASK_ENV: development
    #  FLASK_APP: Solar
    #  SECRET_KEY: solas90866    
#    ports:
#      - "5000:5000"
#    depends_on:
#      - solar-db
#      - adminer-bd
#    links:
#        - solar-db
#    deploy:
#      resources:
#        limits:
#          #cpus: '0.50'
#          memory: 1024M
#        reservations:
#          #cpus: '0.25'
#          memory: 512M

#    networks:
#      solar-network:
#        ipv4_address: 172.19.0.2

  solar-front:
    container_name: solar-front-container
    build: /home/cis/elizabeth/solar_front
    image: solar-front:latest
    #environment:
    #  MYSQL_HOST: ${MYSQL_HOST}
    #  MYSQL_USER: admin
    #  MYSQL_PASSWORD: root12345
    #  MYSQL_DB: solardb
    #  FLASK_ENV: development
    #  FLASK_APP: Solar
    #  SECRET_KEY: solas90866
    ports:
      - "81:8000"
    depends_on:
      - solar-db
  #    - solar-web
    #links:
    #    - solar-web
#    deploy:
#      resources:
#        limits:
#          #cpus: '0.50'
#          memory: 1024M
#        reservations:
#          #cpus: '0.25'
#          memory: 512M

    networks:
      solar-network:
        ipv4_address: 172.19.0.3


networks:
  solar-network:
    driver: bridge
    #driver_opts:
    #    parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
